development:
  adapter: mysql2
  encoding: utf8
  reconnect: false
  database: dya_development
  pool: 5
  username: root
  password:

test: &test
  adapter: mysql2
  encoding: utf8
  reconnect: false
  database: dya_test
  pool: 5
  username: root
  password:

production:
  adapter: mysql2
  encoding: utf8
  reconnect: false
  database: dya_production
  pool: 5
  username: root
  password: